accounts/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView
from accounts.views import signup

urlpatterns = [
    path("login/", LoginView.as_view(), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("signup/", signup, name="signup"),
]

companies/urls.py
from django.urls import path

from companies.views import (
    CompanyCreateView,
    CompanyDetailView,
    CompanyListView,
    CompanyUpdateView,
)


urlpatterns = [
    path("", CompanyListView.as_view(), name="list_companies"),
    path("<int:pk>/", CompanyDetailView.as_view(), name="show_company"),
    path("create/", CompanyCreateView.as_view(), name="create_company"),
    path(
        "<int:pk>/update/", CompanyUpdateView.as_view(), name="update_company"
    ),
]

projects/urls.py
from django.urls import path
from projects.views import (
    ProjectCreateView,
    ProjectDetailView,
    ProjectListView,
    search_project,
)

urlpatterns = [
    path("", ProjectListView.as_view(), name="list_projects"),
    path("<int:pk>/", ProjectDetailView.as_view(), name="show_project"),
    path("create/", ProjectCreateView.as_view(), name="create_project"),
    path("search/", search_project, name="search"),
]

tasks/urls.py
from django.urls import path
from tasks.views import TaskListView, TaskUpdateView, TaskCreateView

urlpatterns = [
    path("mine/", TaskListView.as_view(), name="show_my_tasks"),
    path("create/", TaskCreateView.as_view(), name="create_task"),
    path("<int:pk>/complete/", TaskUpdateView.as_view(), name="complete_task"),
]

tracker/urls.py
from django.contrib import admin
from django.urls import path, include, reverse_lazy
from django.views.generic.base import RedirectView

urlpatterns = [
    path("admin/", admin.site.urls),
    path("projects/", include("projects.urls")),
    path(
        "",
        RedirectView.as_view(url=reverse_lazy("list_projects")),
        name="home",
    ),
    path("accounts/", include("accounts.urls")),
    path("tasks/", include("tasks.urls")),
    path("companies/", include("companies.urls")),
]

accounts/models.py
# Create your models here.

companies/models.py
from django.db import models
from projects.models import User

# Create your models here.


class Company(models.Model):
    name = models.CharField(max_length=50)
    planner = models.ForeignKey(
        User, related_name="companies", null=True, on_delete=models.SET_NULL
    )
    projects = models.ManyToManyField(
        "projects.Project", related_name="companies"
    )

    def __str__(self):
        return self.name

projects/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.


class Project(models.Model):
    name = models.CharField(max_length=200)
    description = models.TextField()
    members = models.ManyToManyField(User, related_name="projects")

    def __str__(self):
        return self.name

tasks/models.py
from django.db import models
from projects.models import User

# Create your models here.


class Task(models.Model):
    name = models.CharField(max_length=200)
    start_date = models.DateTimeField()
    due_date = models.DateTimeField()
    is_completed = models.BooleanField(default=False)
    project = models.ForeignKey(
        "projects.Project", related_name="tasks", on_delete=models.CASCADE
    )
    assignee = models.ForeignKey(
        User, related_name="tasks", null=True, on_delete=models.SET_NULL
    )

    def __str__(self):
        return self.name

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.contrib.auth import login

# Create your views here.


def signup(request):
    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            username = request.POST["username"]
            password = request.POST["password1"]
            user = User.objects.create_user(
                username=username, password=password
            )
            user.save()
            login(request, user)
            return redirect("home")
    else:
        form = UserCreationForm(request.POST)
    context = {"form": form}
    return render(request, "registration/signup.html", context)

companies/views.py
# from django.shortcuts import render
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView
from django.contrib.auth.mixins import LoginRequiredMixin
from companies.models import Company

# Create your views here.


class CompanyListView(LoginRequiredMixin, ListView):
    model = Company
    template_name = "companies/list.html"
    paginate_by = 5

    def get_queryset(self):
        return Company.objects.filter(planner=self.request.user)


class CompanyDetailView(LoginRequiredMixin, DetailView):
    model = Company
    template_name = "companies/detail.html"

    def get_queryset(self):
        return Company.objects.filter(planner=self.request.user)


class CompanyCreateView(LoginRequiredMixin, CreateView):
    model = Company
    template_name = "companies/create.html"
    fields = ["name", "projects"]

    def form_valid(self, form):
        company = form.save(commit=False)
        company.planner = self.request.user
        company.save()
        form.save_m2m()
        return redirect("show_company", pk=company.id)


class CompanyUpdateView(LoginRequiredMixin, UpdateView):
    model = Company
    template_name = "companies/update.html"
    fields = ["name", "projects"]

    def get_queryset(self):
        return Company.objects.filter(planner=self.request.user)

    def get_success_url(self):
        return reverse_lazy("show_company", args=[self.object.id])

projects/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from projects.models import Project
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic.edit import CreateView
from tasks.models import Task

# Create your views here.


class ProjectListView(LoginRequiredMixin, ListView):
    model = Project
    template_name = "projects/list.html"
    paginate_by = 10

    def get_queryset(self):
        return Project.objects.filter(members=self.request.user)


class ProjectDetailView(LoginRequiredMixin, DetailView):
    model = Project
    template_name = "projects/detail.html"


class ProjectCreateView(LoginRequiredMixin, CreateView):
    model = Project
    template_name = "projects/create.html"
    fields = ["name", "description", "members"]

    def get_success_url(self):
        return reverse_lazy("show_project", args=[self.object.id])


def search_project(request):
    if request.method == "POST":
        searched = request.POST["searched"]
        projects = Project.objects.filter(name__contains=searched)
        tasks = Task.objects.filter(name__contains=searched)
        return render(
            request,
            "projects/search.html",
            {"searched": searched, "projects": projects, "tasks": tasks},
        )
    else:
        return render(request, "projects/search.html", {})

tasks/views.py
# from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic.list import ListView
from django.views.generic.edit import UpdateView, CreateView
from django.contrib.auth.mixins import LoginRequiredMixin
from tasks.models import Task

# Create your views here.


class TaskListView(LoginRequiredMixin, ListView):
    model = Task
    template_name = "tasks/list.html"
    paginate_by = 10

    def get_queryset(self):
        return Task.objects.filter(assignee=self.request.user)


class TaskCreateView(LoginRequiredMixin, CreateView):
    model = Task
    template_name = "tasks/create.html"
    fields = ["name", "start_date", "due_date", "project", "assignee"]

    def get_success_url(self):
        return reverse_lazy("show_project", args=[self.object.project.id])


class TaskUpdateView(UpdateView):
    model = Task
    fields = ["is_completed"]

    def get_success_url(self):
        return reverse_lazy("show_my_tasks")

companies/templates/companies/create.html
{% extends 'base.html' %}
{% block content %}
    <main>
        <div class="project-form">
            <h1>Add a company</h1>
            <form method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <button>Add</button>
            </form>
        </div>
    </main>
{% endblock content %}

companies/templates/companies/detail.html
{% extends 'base.html' %}
{% block content %}
<main>
    <div class="project-detail">
        <a href="{% url 'update_company' company.id %}">Update company plan</a>
        <h1>{{ company.name }}</h1>
        <h2>Projects</h2>
        <a href="{% url 'create_project' %}">Create a new project</a>
        {% if company.projects.all|length != 0 %}
        <table>
            <thead>
                <tr>
                    <th>Name</th>
                    <th>Number of tasks</th>
                </tr>
            </thead>
            <tbody>
                {% for project in company.projects.all %}
                <tr>
                    <td>
                        <a href="{% url 'show_project' project.id %}">{{ project.name }}
                        </a>
                    </td>
                    <td>{{ project.tasks.all|length }}</td>
                    {% endfor %}
            </tbody>
        </table>
        {% else %}
        <p>No assigned project to this company yet</p>
        {% endif %}
    </div>
</main>
{% endblock content %}

companies/templates/companies/list.html
{% extends 'pagination.html' %}
{% block content %}
<main>
    <div class="project-list">
        <h1>Company</h1>
        <a href="{% url 'create_company' %}">Add a new company</a>
        {% if company_list|length == 0 %}
            <p>No companies yet</p>
        {% else %}
            <table>
                <thead>
                    <tr>
                        <th>Name</th>
                        <th>Number of projects</th>
                    </tr>
                </thead>
                <tbody>
                    {% for company in company_list %}
                        <tr>
                            <td>
                                <a href="{% url 'show_company' company.id %}">{{ company.name }}</a>
                            </td>
                            <td>{{ company.projects.all|length }}</td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        {% endif %}
    </div>
</main>
{% endblock content %}

companies/templates/companies/update.html
{% extends 'base.html' %}
{% block content %}
<main>
    <div class="project-form">
        <h1>Update company plan</h1>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button>Update</button>
        </form>
    </div>
</main>
{% endblock content %}

projects/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Tracker</title>
    <link rel="stylesheet" href="{% static 'css/app.css' %}">
    <link rel="stylesheet" href="{% static 'fontawesomefree/css/all.min.css' %}">
</head>

<body>
    <header>
        <nav>
            <ul>
                {% if user.is_authenticated %}
                <li>
                    <a href="{% url 'home' %}">
                        <i class="fa-solid fa-house-chimney"></i>
                    </a>
                </li>
                <li>
                    <a href="{% url 'show_my_tasks' %}">My tasks</a>
                </li>
                <li>
                    <a href="{% url 'list_projects' %}">My projects</a>
                </li>
                <li>
                    <a href="{% url 'list_companies' %}">Company</a>
                </li>
                <li>
                    <form action="{% url 'search' %}" method="post">
                        {% csrf_token %}

                        <input type="search" name="searched" placeholder="Search">
                        <button type="submit">Search</button>
                    </form>
                </li>
                <li>
                    <a href="{% url 'logout' %}">Logout</a>
                </li>
                {% else %}
                <li>
                    <a href="{% url 'login' %}">Login</a>
                </li>
                <li>
                    <a href="{% url 'signup' %}">Signup</a>
                </li>
                {% endif %}
            </ul>
        </nav>
    </header>
    {% block content %}
    {% endblock content %}
    </br>
    {% block pagination %}
    {% endblock pagination %}
</body>

</html>

projects/templates/pagination.html
{% extends 'base.html' %}
{% block pagination %}
<div class="paginate">
    <span class="step-links">
        {% if page_obj.has_previous %}
        <a href="?page=1">&laquo; first</a>
        <a href="?page={{ page_obj.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}
        </span>

        {% if page_obj.has_next %}
        <a href="?page={{ page_obj.next_page_number }}">next</a>
        <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
        {% endif %}
    </span>
</div>

{% endblock pagination %}

projects/templates/projects/create.html
{% extends 'base.html' %}
{% block content %}
    <main>
        <div class="project-form">
            <h1>Create a new project</h1>
            <form method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <button>Create</button>
            </form>
        </div>
    </main>
{% endblock content %}

projects/templates/projects/detail.html
{% extends 'base.html' %}
{% block content %}
{% load markdownify %}
<main>
    <div class="project-detail">
        <h1>{{ project.name }}</h1>
        {{ project.description|markdownify }}
        <h2>Companies</h2>
        {% for company in project.companies.all %}
        <a href="{% url 'show_company' company.id %}">{{ company.name }}</a>
        {% endfor %}
        <h2>Tasks</h2>
        <a href="{% url 'create_task' %}">Create a new task</a>
        {% if project.tasks.all|length != 0 %}
        <table>
            <thead>
                <tr>
                    <th>Name</th>
                    <th>Assignee</th>
                    <th>Start date</th>
                    <th>Due date</th>
                    <th>Is completed</th>
                </tr>
            </thead>
            <tbody>
                {% for task in project.tasks.all %}
                <tr>
                    <td>{{ task.name }}</td>
                    <td>{{ task.assignee }}</td>
                    <td>{{task.start_date }}</td>
                    <td>{{ task.due_date }}</td>
                    {% if task.is_completed %}
                    <td>yes</td>
                    {% else %}
                    <td>no</td>
                    {% endif %}
                </tr>
                {% endfor %}
            </tbody>
        </table>
        {% else %}
        <p>This project has no tasks</p>
        {% endif %}
    </div>
</main>
{% endblock content %}

projects/templates/projects/list.html
{% extends 'pagination.html' %}
{% block content %}
<main>
    <div class="project-list">
        <h1>My Projects</h1>
        <a href="{% url 'create_project' %}">Create a new project</a>
        {% if project_list|length == 0 %}
        <p>You are not assigned to any projects</p>
        {% else %}
        <table>
            <thead>
                <tr>
                    <th>Name</th>
                    <th>Number of tasks</th>
                </tr>
            </thead>
            <tbody>
                {% for project in project_list %}
                <tr>
                    <td>
                        <a href="{% url 'show_project' project.id %}">{{ project.name }}</a>
                    </td>
                    <td>{{ project.tasks.all|length }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
        {% endif %}
    </div>
</main>

{% endblock content %}

projects/templates/projects/search.html
{% extends 'base.html' %}
{% block content %}
    <main>
        <div class="project-list">
        {% if searched %}
            <h1>Result of search {{ searched }}</h1>
            {% if projects|length == 0 and tasks|length == 0 %}
                <p>No results! Please try another keyword.</p>
            {% else %}
                {% if projects|length != 0 %}
                <h2>My projects:</h2>
                <table>
                    <thead>
                        <tr>
                            <th>Name</th>
                            <th>Number of tasks</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for project in projects %}
                            <tr>
                                <td>
                                    <a href="{% url 'show_project' project.id %}">{{ project.name }}</a>
                                </td>
                                <td>{{ project.tasks.all|length }}</td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
                {% endif %}
            </br>
                {% if tasks|length != 0 %}
                <h2>My tasks:</h2>
                <table>
                    <thead>
                        <tr>
                            <th>Name</th>
                            <th>Start date</th>
                            <th>End date</th>
                            <th>Is completed</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for task in tasks %}
                            <tr>
                                <td>{{ task.name }}</td>
                                <td>{{ task.start_date }}</td>
                                <td>{{ task.due_date }}</td>
                                {% if task.is_completed == True %}
                                    <td>Done</td>
                                {% else %}
                                    <td>
                                        <form method="post" action="{% url 'complete_task' task.id %}">
                                            {% csrf_token %}
                                            <input type="hidden" value="True" name="is_completed">
                                            <button>Complete</button>
                                        </form>
                                    </td>
                                {% endif %}
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
                {% endif %}
            {% endif %}
        {% else %}
            <h1>Please enter a keyword to search for projects</h1>
        {% endif %}
        </div>
    </main>

{% endblock content %}

tasks/templates/tasks/create.html
{% extends 'base.html' %}
{% block content %}
    <main>
        <div class="task-form">
            <h1>Create a new task</h1>
            <form method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <button>Create</button>
            </form>
        </div>
    </main>
{% endblock content %}

tasks/templates/tasks/list.html
{% extends 'pagination.html' %}
{% block content %}
    <main>
        <div class="my-tasks-list">
            <h1>My Tasks</h1>
            {% if task_list|length != 0 %}
                <table>
                    <thead>
                        <tr>
                            <th>Name</th>
                            <th>Start date</th>
                            <th>End date</th>
                            <th>Is completed</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for task in task_list %}
                            <tr>
                                <td>{{ task.name }}</td>
                                <td>{{ task.start_date }}</td>
                                <td>{{ task.due_date }}</td>
                                {% if task.is_completed == True %}
                                    <td>Done</td>
                                {% else %}
                                    <td>
                                        <form method="post" action="{% url 'complete_task' task.id %}">
                                            {% csrf_token %}
                                            <input type="hidden" value="True" name="is_completed">
                                            <button>Complete</button>
                                        </form>
                                    </td>
                                {% endif %}
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            {% else %}
                <p>You have no tasks</p>
            {% endif %}
        </div>
    </main>
{% endblock content %}